export const initialRows = [
  {
    id: 1,
    name: "Alex Johnson",
    office: "Office 1",
    team: "Team 1",
    cat1: true,
    cat2: false,
    cat3: true,
  },
  {
    id: 2,
    name: "Jordan Lee",
    office: "Office 2",
    team: "Team 2",
    cat1: true,
    cat2: true,
    cat3: false,
  },
  {
    id: 3,
    name: "Taylor Brooks",
    office: "Office 3",
    team: "Team 3",
    cat1: false,
    cat2: true,
    cat3: true,
  },
  {
    id: 4,
    name: "Chris Diaz",
    office: "Office 4",
    team: "Team 4",
    cat1: false,
    cat2: true,
    cat3: false,
  },
  {
    id: 5,
    name: "Ava White",
    office: "Office 5",
    team: "Team 5",
    cat1: true,
    cat2: false,
    cat3: false,
  },
  {
    id: 6,
    name: "Sam Carter",
    office: "Office 6",
    team: "Team 6",
    cat1: false,
    cat2: true,
    cat3: false,
  },
  {
    id: 7,
    name: "Logan Cruz",
    office: "Office 7",
    team: "Team 7",
    cat1: true,
    cat2: true,
    cat3: true,
  },
  {
    id: 8,
    name: "Morgan Patel",
    office: "Office 8",
    team: "Team 8",
    cat1: true,
    cat2: true,
    cat3: true,
  },
  {
    id: 9,
    name: "Jamie Smith",
    office: "Office 9",
    team: "Team 9",
    cat1: true,
    cat2: false,
    cat3: false,
  },
  {
    id: 10,
    name: "Riley Kim",
    office: "Office 10",
    team: "Team 10",
    cat1: true,
    cat2: false,
    cat3: true,
  },
  {
    id: 11,
    name: "Casey Nguyen",
    office: "Office 11",
    team: "Team 11",
    cat1: false,
    cat2: false,
    cat3: true,
  },
  {
    id: 12,
    name: "Quinn Rivera",
    office: "Office 12",
    team: "Team 12",
    cat1: true,
    cat2: true,
    cat3: false,
  },
  {
    id: 13,
    name: "Dana Flores",
    office: "Office 13",
    team: "Team 13",
    cat1: true,
    cat2: false,
    cat3: true,
  },
  {
    id: 14,
    name: "Avery Brown",
    office: "Office 14",
    team: "Team 14",
    cat1: false,
    cat2: true,
    cat3: false,
  },
  {
    id: 15,
    name: "Cory Bennett",
    office: "Office 15",
    team: "Team 15",
    cat1: true,
    cat2: true,
    cat3: true,
  },
];

export const demoTree = [
  {
    id: "office-1",
    label: "Office 1 (3)",
    type: "group",
    children: [
      {
        id: "office1-team-1",
        label: "Team 1 (4)",
        type: "group",
        children: [
          {
            id: "office1-team-1-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office1-team-1-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
          {
            id: "office1-team-1-u-3",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏻‍💼",
          },
          {
            id: "office1-team-1-u-4",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
        ],
      },
      {
        id: "office1-team-2",
        label: "Team 2 (2)",
        type: "group",
        children: [
          {
            id: "office1-team-2-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office1-team-2-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
        ],
      },
      {
        id: "office1-team-3",
        label: "Team 3 (6)",
        type: "group",
        children: [
          {
            id: "office1-team-3-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office1-team-3-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
          {
            id: "office1-team-3-u-3",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏻‍💼",
          },
          {
            id: "office1-team-3-u-4",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
          {
            id: "office1-team-3-u-5",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
          {
            id: "office1-team-3-u-6",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
        ],
      },
    ],
  },
  {
    id: "office-2",
    label: "Office 2 (4)",
    type: "group",
    children: [
      {
        id: "office-2-team-1",
        label: "Team 1 (4)",
        type: "group",
        children: [
          {
            id: "office2-team1-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office2-team1-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
          {
            id: "office2-team1-u-3",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏻‍💼",
          },
          {
            id: "office2-team1-u-4",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
        ],
      },
      {
        id: "office-2-team-2",
        label: "Team 2 (2)",
        type: "group",
        children: [
          {
            id: "office2-team2-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office2-team2-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
        ],
      },
      {
        id: "office-2-team-3",
        label: "Team 3 (6)",
        type: "group",
        children: [
          {
            id: "office2-team3-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office2-team3-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
          {
            id: "office2-team3-u-3",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏻‍💼",
          },
          {
            id: "office2-team3-u-4",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
          {
            id: "office2-team3-u-5",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
          {
            id: "office2-team3-u-6",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "👩🏼‍💼",
          },
        ],
      },
      {
        id: "office-2-team-4",
        label: "Team 4 (2)",
        type: "group",
        children: [
          {
            id: "office2-team4-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
          {
            id: "office2-team4-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏻‍💼",
          },
        ],
      },
    ],
  },
  {
    id: "office-3",
    label: "Office 3 (4)",
    type: "group",
    children: [
      {
        id: "office-3-team-1",
        label: "Team 1",
        type: "group",
        children: [
          {
            id: "office3-team1-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-3-team-2",
        label: "Team 2",
        type: "group",
        children: [
          {
            id: "office3-team2-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-3-team-3",
        label: "Team 3",
        type: "group",
        children: [
          {
            id: "office3-team3-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-3-team-4",
        label: "Team 4",
        type: "group",
        children: [
          {
            id: "office3-team4-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
    ],
  },
  {
    id: "office-4",
    label: "Office 4 (2)",
    type: "group",
    children: [
      {
        id: "office-4-team-1",
        label: "Team 1",
        type: "group",
        children: [
          {
            id: "office4-team1-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-4-team-2",
        label: "Team 2",
        type: "group",
        children: [
          {
            id: "office4-team2-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
    ],
  },
  {
    id: "office-5",
    label: "Office 5 (4)",
    type: "group",
    children: [
      {
        id: "office-5-team-1",
        label: "Team 1",
        type: "group",
        children: [
          {
            id: "office5-team1-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-5-team-2",
        label: "Team 2",
        type: "group",
        children: [
          {
            id: "office5-team2-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-5-team-3",
        label: "Team 3",
        type: "group",
        children: [
          {
            id: "office5-team3-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-5-team-4",
        label: "Team 4",
        type: "group",
        children: [
          {
            id: "office5-team4-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
    ],
  },
  {
    id: "office-6",
    label: "Office 6 (3)",
    type: "group",
    children: [
      {
        id: "office-6-team-1",
        label: "Team 1",
        type: "group",
        children: [
          {
            id: "office6-team1-u-1",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-6-team-2",
        label: "Team 2",
        type: "group",
        children: [
          {
            id: "office6-team2-u-2",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
      {
        id: "office-6-team-3",
        label: "Team 3",
        type: "group",
        children: [
          {
            id: "office6-team3-u-3",
            label: "Name",
            subtitle: "Job title",
            type: "person",
            avatar: "🧑🏽‍💼",
          },
        ],
      },
    ],
  },
];

export const categories = [
  { id: "cat1", label: "Category 1" },
  { id: "cat2", label: "Category 2" },
  { id: "cat3", label: "Category 3" },
];

export const steps = [
  { id: 1, label: "Step 1" },
  { id: 2, label: "Step 2" },
  { id: 3, label: "Step 3" },
];
